title: [Quasar Neural Network]
description: [A neural network to identify quasars from other objects with similar photometric properties]
theme: jekyll-theme-slate
markdown: kramdown

# Reading Files
include:
  - _pages
